spring:
  application:
    name: avengers
  config:
    use-legacy-processing: true
  profiles:
    active: dev
  jax:
    enabled: false
  data:
    jpa:
      reposirories:
        bootstrap-node: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SprigPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SprigImplicitNamingStrategy
  main:
    allow-bean-definition-overrinding: true
  task:
    execution:
      thread-name-prefix: avengers-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: avengers-scheduling
      pool:
        size: 2
  output:
    ansi:
      console-available: true
server:
  port: 9090
  service:
    session:
      cookie:
        http-only: true
    context-path: /avengers



